app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='users')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('lines/', views.lines, name='lines'),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
]

main/models.py
from django.db import models

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):

    class Meta:
        db_table = "user"

    def __str__(self) -> str:
        return self.username
          

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()
    

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2',
            ]

    username = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'username',
            ]
    username = forms.CharField()

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest

# Create your views here.
def index(request) -> HttpResponse:
    return render(request, 'main/index.html', {'indx':'sdasdasdasdasdadasdadadasdads'})
def lines(request) -> HttpResponse:
    return render(request, 'main/lines.html', {'indx':'sdasdasdasdasdadasdadadasdads'})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .forms import UserLoginForm, UserRegistrationForm, ProfileForm

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main:index'))
    else:   
        form = UserRegistrationForm()

    context = {
        'title': "registration",
        'form': form
    }

    return render(request, 'users/registration.html', context)
 
def login(request):
    
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                messages.success(request ,f"{username}, ви війшли в аккаунт")
                return redirect(reverse('main:index'))
    else:   
        form = UserLoginForm()

    context = {
        'title': "Login",
        'form': form
    }

    return render(request, 'users/login.html', context)

@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse('main:index'))

@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            
            # if request.POST.get('next', None): 
            #     return HttpResponseRedirect(request.POST.get('next'))
            return HttpResponseRedirect(reverse('user:profile'))
    else:   
        form = ProfileForm(instance=request.user)

    context = {
        'title': "Profile",
        'form': form
    }

    return render(request, 'users/profile.html', context)

main/templates/main/index.html
{% extends "base.html" %}
{%load static%}
{% block title %}
    <title>Home</title>
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
      {% for i in indx %}
        
      <div class="card my_cards">
          <div class="card-header">Header
        </div>
            
          <div class="card-body">

            <h5 class="card-title">Dark card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
          <li  class="text-center my_li" style="list-style-type:none;">
            <a href="">
              <span class="iconify" data-icon="mi:link-alt"></span>
            </a>
            <a href="">
              <span class="iconify" data-icon="mi:edit-alt"></span>
            </a>
            <a href="">
            <span class="iconify" data-icon="mi:options-horizontal"></span>
            </a>
          </li>
      
      </div>
      {% endfor %}

    </div>
</div>

<div class="bottom-panel">
    <button type="button" class="btn btn-dark">Dark</button>

</div>
{% endblock content %}

main/templates/main/lines.html
{% extends "base.html" %}
{%load static%}
{% block title %}
    <title>Home</title>
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
      {% for i in indx %}
        
      <div class="card my_cards">
          <div class="card-header">Header
        </div>
            
          <div class="card-body">

            <h5 class="card-title">Dark card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
          <li  class="text-center my_li" style="list-style-type:none;">
            <a href="">
              <span class="iconify" data-icon="mi:link-alt"></span>
            </a>
            <a href="">
              <span class="iconify" data-icon="mi:edit-alt"></span>
            </a>
            <a href="">
            <span class="iconify" data-icon="mi:options-horizontal"></span>
            </a>
          </li>
      
      </div>
      {% endfor %}

    </div>
</div>

<div class="bottom-panel">
    <button type="button" class="btn btn-dark">Dark</button>

</div>
<script src="https://code.iconify.design/3/3.1.0/iconify.min.js"></script>
{% endblock content %}

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %}<title>Document</title>{% endblock title %}
  <link rel="icon" href="{% static 'deps/ico/my.css' %}">
  <link rel="stylesheet" href="{% static 'deps/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'deps/css/my.css' %}">

</head>
<body>
  {% block content %}{% endblock content %}


  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>

  <script src="https://code.iconify.design/3/3.1.0/iconify.min.js"></script>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

users/templates/users/login.html
{% extends "base.html" %}
{%load static%}
{% block title %}
    <title>Login</title>
{% endblock title %}

{% block content %}
<form action="{% url 'users:login' %}" class="login_form" method="post">
<div class="container login_container">
  <div class="row justify-content-center">
    <div class="col-md-4 content-center">   
      {% csrf_token %} 
      <br>
      <div class="form-group">
        <label for="id_username">Username</label>
        <input type="text" name="username" autofocus="" class="form-control" placeholder="Введіть ваше ім'я користувачаі" maxlength="150" required="" id="id_username">
      </div>

      <div class="form-group">
        <label for="id_password">Password</label>
        <input type="password" name="password" autocomplete="current-password" class="form-control" placeholder="Введіть ваш пароль" required="" id="id_password">
      </div>

      <div class="form-group form-check">
        <input type="checkbox" class="form-check-input"
        id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Запам'ятати мене</label>
      </div>

      <a href="#">Забув пароль?</a>      
    </div>
  </div>
</div>
</form>
{% endblock content %}

users/templates/users/registration.html
{% extends "base.html" %}
{%load static%}
{% block title %}
    <title>Registration</title>
{% endblock title %}

{% block content %}
<form action="{% url 'users:registration' %}" class="login_form" method="post">
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-4 content-center">   
      {{form}}
      
    </div>
  </div>
</div>
</form>
{% endblock content %}